### ISSUE TITLE
Primordial Flesh healing seems to be really inconsistent

### ISSUE THREAD

**Issue by MightyW0lf** [KevinfromHP/KevinsAdditionalItems#4]
Healing from the item doesn't always ramp up on high velocity events (such as Artificer's Special, falling, etc. - see the video). The healing is also often present when standing completely still. [Demonstration video.](https://youtu.be/81mgb1hRiUU)

Mods:

* bbepis-BepInExPack-5.3.1
* tristanmcpherson-R2API-2.5.14
* ThinkInvis-TILER2-3.0.4
* **KevinfromHPCustomerService-Kevins_Additional_Items-3.5.12**
* Harb-DebugToolkit-3.4.2

**Comment by KevinfromHP** [comment]
Hey, this is just to let you know that I've seen this and I'm working on the issue as we speak. Thanks for the feedback, I appreciate it! If you are in the ROR2 modding Discord, pop me at @Kevin from HP Customer Service#0569 and I'd be happy to hook you up with a debug build to test at your leisure.

**Comment by KevinfromHP** [comment]
Hey! I figured out what was causing the issues. The stats were only changing when the game called for them to, but since the velocity changes every frame, this led to inconsistencies. The new build should be available in the repositories **Build** folder, the Debug zip. I'll keep this thread open for a couple more days if you find any other issues.

Thanks for your feedback!

**Comment by MightyW0lf** [comment]
I get this error when i try to add the build manually (using the r2modman). (this error happens for the Release build as well)

![image](https://user-images.githubusercontent.com/30864557/105183478-89981200-5b2e-11eb-8eaa-a040881da4e0.png)

**Comment by KevinfromHP** [comment]
Hey, I should have mentioned that this does not make a local build. You can replace the items in the r2modman downloaded file with these ones.
